### ISSUE TITLE
About the downstream filtering of GATK-SV pipeline

### ISSUE THREAD

**Issue by elitefugua** [kkaivola/LBD_FTD_Structural_variants#1]
Hello, @kkaivola . I have read the paper “Genome-wide structural variant analysis identifies risk loci for non-Alzheimer’s dementias”, and I am working on a similar research about the structure variants. In the method section you mentioned that the downstream filtering of the GATK-SV pipeline had been conducted. However, it seems that the module 07 of GATK-SV, which can be used to apply downstream filtering steps (minGQ filtering, FilterOutlierSamples, BatchEffect, and FilterCleanupQualRecalibration) to the cleaned VCF, is still in development. Thus, I wonder how these downstream filtering were performed in your study.
Thank you very much for your attention and consideration.
Looking forward to your reply.

**Comment by kkaivola** [comment]
Hello, @elitefugua 

The latest GATK-SV version we used was gatk-sv-0.13-beta.2021.3.15 so unfortunately I can't give you a direct answer regarding how to run the module 07 in the current version. In the development version we used, we had to run most modules manually and separately. For module 7, we used the scripts and lookup module from the gatk-sv github repository. This did of course require some manual configuration and we received support from the GATK-SV development team.

**Comment by elitefugua** [comment]
Hello, @kkaivola .
Thanks a lot for your reply! Can we apply to you for the scripts and manual configuration for performing the downstream filtering in your previously published study? We would be very grateful if you could  help us.

**Comment by kkaivola** [comment]
Hi, you have to do the configuration on your computer cluster/server with your own files and I would strongly recommend using the latest GATK-SV version, not the older beta versions we ran. So unfortunately I can't help you with that. However, the scripts should be at GATK-SV's github page https://github.com/broadinstitute/gatk-sv/tree/main (look at scripts and src directories). The GATK-SV pipeline is complex and running it manually adds another layer of complexity, so if possible, I would suggest following GATK-SV's latest guidance and using Cromwell/Terra to run the pipeline. You can get further assistance from the GATK-SV team. Best of luck!
